### ISSUE TITLE
Update Bottom Tab Navigation Bar to New Design

### ISSUE THREAD

**Issue by ahmadao2214** [Dubletar/BernrApp#3]
@Dubletar Do you have a link to the new design?

**Comment by Dubletar** [comment]
@ahmadao2214, what you can do for now is to find  two random icons to place, as placeholders for the actual icons we're going to use. 

The two sections will be "Menu" and "Moments".

So the icons should be in order from left to right:
1. Menu
2. Moments
3. Grid
4. Matches
5. Messages

**Comment by ahmadao2214** [comment]
Pull Request to resolve this issue has been opened [here](https://github.com/Dubletar/BernrApp/pull/14)

@Dubletar Check it out when you get a chance please
